### ISSUE TITLE
This is bullcrap

### ISSUE THREAD

**Issue by ticki** [Arkanosis/microstatus#1]
It makes claims in the README about all sorts of stuff. Hell, it even is on crates.io and has a travis, yet it's nothing but a command-line program with a `--help` flag. It's like not-even-trying vaporware. At the very least remove the claims and make it very clear, it is barely started yet, if you're in good faith and not trying to scam people.

**Comment by Arkanosis** [comment]
Oh, wow! Seriously?

Feel free to open another issue on whichever subject you would like me to address, _with appropriate language and tone_ and I'd be happy to spend some of my time _as a benevolent_ to please you if I can.
